name: learn_retrofit
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  logger: ^2.4.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.3
  flutter_lints: ^4.0.0

flutter:

  
  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700
 